name: Update dependency graph
on:
  push:
    branches: [master]

jobs:
  update_dependency_graph:
    runs-on: ubuntu-latest
    steps:
    - name: Update dependency graph
      if: github.ref == 'refs/heads/master'
      uses: advanced-security/maven-dependency-submission-action@v2.0.1
